services:
  - type: web
    name: shapehub
    runtime: node
    plan: free
    buildCommand: "npm install --omit=dev"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
